version: '3.9'

services:
  protonmail-bridge:
    image: ghcr.io/belphemur/protonmail-bridge
    # build:
    #  context: ./build
    #  dockerfile: Dockerfile
    container_name: pm_bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    environment:
      - UID=900
    restart: unless-stopped
    stdin_open: true 
    tty: true
    volumes:
      - ./data:/home/protonmail
