name: build from source

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/build.yaml
      - build/*
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - build/*

env:
  DOCKER_REPO: ghcr.io/belphemur/protonmail-bridge
  DOCKER_REPO_DEV: ghcr.io/belphemur/protonmail-bridge-dev
  PLATFORMS: linux/amd64,linux/arm64/v8
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        id: version
        run: echo "version=$(cat build/VERSION)" >> $GITHUB_OUTPUT
      - name: Set repo
        id: repo
        run: if [[ $GITHUB_REF == "refs/heads/master" ]]; then echo "repo=${DOCKER_REPO}" >> $GITHUB_OUTPUT; else echo "repo=${DOCKER_REPO_DEV}" >> $GITHUB_OUTPUT; fi
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.repo.outputs.repo }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.repo.outputs.version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build image without push to registry
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: localhost:5000/protonmail-bridge:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: localhost:5000/protonmail-bridge:latest
          fail-build: true
          severity-cutoff: critical
          acs-report-enable: true
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image ${{ matrix.image }}
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
