name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        DOCKERHUB_REPOSITORY: shenxn/protonmail-bridge
