name: build

on:
  push:
    branches:
      - master
      - dev

env:
  DOCKER_TAG: shenxn/protonmail-bridge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Env
        run: bash set-env.sh
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: shenxn/protonmail-bridge
          tags: ${{ env.TAGS }}
          add_git_labels: true
