name: update check

on:
  push:
    branches:
    - update-check
  schedule:
  - cron: '0 0 * * *'  # runs everyday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: Check Update
      run: bash check-update.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
