name: update check

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/update-check.yaml
      - update-check.sh
  schedule:
  - cron: '0 0 * * *'  # runs everyday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Update
      run: bash update-check.sh
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
